# Generated by Django 2.2.7 on 2019-12-24 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191224_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realization',
            name='comment',
            field=models.CharField(max_length=50, verbose_name='Замечания'),
        ),
    ]
