# Generated by Django 2.2.7 on 2019-12-24 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20191224_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='pasport_data',
            field=models.CharField(max_length=100, verbose_name='Паспортные данные'),
        ),
    ]
